Rails.configuration.search_filter_default = 'full'
Rails.configuration.search_filter_corepwn = 'cpwn'
Rails.configuration.search_filter_ml = 'ml'
Rails.configuration.search_filter_aligned_postfix = '-a'
Rails.configuration.search_filter_default_key = 'search_nofilter'
Rails.configuration.search_filter_corepwn_key = 'corepwn_aligned'
Rails.configuration.search_filter_ml_key = 'ml_aligned'
